### ISSUE TITLE
path problem with gunicorn 

### ISSUE THREAD

**Issue by Alexconte31** [edissyum/opencaptureforinvoices#23] opened 2020-11-05 11:28 UTC
Hello, 
When i finished the installation i got this problem:
/etc/systemd/system/OCForInvoices-web.service:8: Executable "gunicorn" not found in path "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
What path should i add for it to work ?

Regards.

**Comment by nathan30** [comment] 2020-11-05 13:12
Hi ! 

Which distro you're using ? Did you have any error while running the Makefile ?

And could you give me the return of the following command please ? 

`which gunicorn`

**Comment by Alexconte31** [comment] 2020-11-05 13:57
Hello, i am on debian 10, the which gunicorn return nothing. 
I did have some errors while running the make file indeed.

**Comment by nathan30** [comment] 2020-11-05 14:08
There is an issue on the 0.7.5 caused by an apt package. It will be fixed on the next version. On the `bin/install/apt-requirements.txt` could you remove the libmagickwand-dev line ? 

To start fresh, I recommand you to restart the installation from scratch, and remove the line just before running the Makefile. 

Open-Capture For Invoices could be connected to Maarch Courrier for now

**Comment by Alexconte31** [comment] 2020-11-05 14:11
I will start again from scratch, and i will remove that line.

**Comment by Alexconte31** [comment] 2020-11-05 14:22
I still have the same error. Maybe i should install an older version of it.

**Comment by nathan30** [comment] 2020-11-05 14:24
Could you please use the following command and send me the file after ? 

`sudo ./Makefile > makefile_out.log`

(you just have to press enter after launching the command to answer the first question about systemd or supervisor)

**Comment by Alexconte31** [comment] 2020-11-05 14:31
here is the file. 
[makefile_out.log](https://github.com/edissyum/opencaptureforinvoices/files/5494979/makefile_out.log)

**Comment by nathan30** [comment] 2020-11-05 15:20
Did you wait for the end of the script ? Because I see it stopped after collecting pyocr..

I think it could works with apache2 but I dont test it

**Comment by Alexconte31** [comment] 2020-11-05 16:29
It stopped indeed, i will try again and send you the log file tomorrow, probably. 

Thank you.

**Comment by Alexconte31** [comment] 2020-11-20 14:48
Hello, 
I tired the installation again and i got this error this time:

Running setup.py install for psycopg2 ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-p7awuzvf/psycopg2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-p7awuzvf/psycopg2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-b_9i83if/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7/psycopg2
         cwd: /tmp/pip-install-p7awuzvf/psycopg2/
    Complete output (36 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/psycopg2
    copying lib/_lru_cache.py -> build/lib.linux-x86_64-3.7/psycopg2
    copying lib/errorcodes.py -> build/lib.linux-x86_64-3.7/psycopg2
    copying lib/extensions.py -> build/lib.linux-x86_64-3.7/psycopg2
    copying lib/compat.py -> build/lib.linux-x86_64-3.7/psycopg2
    copying lib/sql.py -> build/lib.linux-x86_64-3.7/psycopg2
    copying lib/extras.py -> build/lib.linux-x86_64-3.7/psycopg2
    copying lib/_range.py -> build/lib.linux-x86_64-3.7/psycopg2
    copying lib/errors.py -> build/lib.linux-x86_64-3.7/psycopg2
    copying lib/_json.py -> build/lib.linux-x86_64-3.7/psycopg2
    copying lib/pool.py -> build/lib.linux-x86_64-3.7/psycopg2
    copying lib/__init__.py -> build/lib.linux-x86_64-3.7/psycopg2
    copying lib/tz.py -> build/lib.linux-x86_64-3.7/psycopg2
    copying lib/_ipaddress.py -> build/lib.linux-x86_64-3.7/psycopg2
    running build_ext
    building 'psycopg2._psycopg' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/psycopg
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DPSYCOPG_VERSION=2.8.6 (dt dec pq3 ext lo64) -DPG_VERSION_NUM=110009 -DHAVE_LO64=1 -I/usr/include/python3.7m -I. -I/usr/include/postgresql -I/usr/include/postgresql/11/server -c psycopg/psycopgmodule.c -o build/temp.linux-x86_64-3.7/psycopg/psycopgmodule.o -Wdeclaration-after-statement
    unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
    
    It appears you are missing some prerequisite to build the package from source.
    
    You may install a binary package by installing 'psycopg2-binary' from PyPI.
    If you want to install psycopg2 from source, please install the packages
    required for the build and try again.
    
    For further information please check the 'doc/src/install.rst' file (also at
    <https://www.psycopg.org/docs/install.html>).
    
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-p7awuzvf/psycopg2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-p7awuzvf/psycopg2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-b_9i83if/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7/psycopg2 Check the logs for full command output.

**Comment by nathan30** [comment] 2020-11-26 08:58
Which debian version do you use ? 
I just try on debian 10.6, following the README and there is no issue while launching the Makefile. 

From what I see on the error, try `sudo pip3 install psycopg2-binary`

**Closed** 2020-12-08 10:50 UTC

**Comment by Alexconte31** [comment] 2020-12-09 09:02
Hello,
 My apologies for the delay, but I am also using debian 10.6, I also tried on new Debian 10.6 VM and it is working perfectly fine indeed. Is it possible it happened because I also installed Maarch courrier on the same machine. Wouldn't it be better to install Opencaptureforinvoices on a machine and Opencaptureforinvoices on another one ?

Thank you.

**Comment by nathan30** [comment] 2020-12-09 09:28
Glad to hear that you manager to get it works ! 
Basing on the test I've done, I also have errors with Maarch installed in the same machine because apache and nginx create conflicts :/

**Comment by Alexconte31** [comment] 2020-12-09 09:36
Do you have errors like mine or other errors ? So i think my guess is right and have the two softwares installed on two different machine.

**Comment by nathan30** [comment] 2020-12-09 13:08
I don't remember the errors I had..

**Comment by Alexconte31** [comment] 2020-12-09 13:29
I manage to fix my errors with this :
sudo apt-get install build-essential libssl-dev libffi-dev python-dev 

I will try to force apache to listen to another port than 80 to see if I can run apache2 and nginx at the same time and use maarchcourrier and opencaptureforinvoices on the same machine.

Thanks for your help.

**Comment by nathan30** [comment] 2020-12-09 13:56
Okay, do not hesitate to write a tutorial on how you do it (with the package you need etc...) if you have the time :+1: 
Thanks in advance
(the wiki is under construction, in French for now)

**Comment by Alexconte31** [comment] 2020-12-09 14:53
If i manage to make it work i will try to write a good tutorial. Opencapture works fine but Maarch is bugging since I change the port of apache2.

**Comment by nathan30** [comment] 2020-12-09 14:54
Which version of Maarch do you use ?

**Comment by Alexconte31** [comment] 2020-12-15 09:03
Hello, I am using maarchcourrier 19.04 and everything is working ( opencapture and maarch ) fine. 
But now, I don't know how opencapture work. Is there documentation ? Because i wasn't able to find it, but once i am logged into opencapture, i upload a facture but that is all. 

Regards

**Comment by nathan30** [comment] 2020-12-15 12:22
A documentation will be out by the 01/01/2021

**Comment by nathan30** [comment] 2020-12-15 16:50
Here is the start of the document, Maybe you could find some help. You'll have some informations about the interface in the "demo" chapter. The installation is not finished, same for the technical tutorial (about config files etc...)

If you need more help, do not hesitate. Some informations are also available into the README (for example to process automatically files after Open-Capture Splitter)

https://kutt.it/GitBook
